service: nexabit-backend-dev

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2

functions:
  user:
    handler: handler.getUser
    events:
      - http:
          path: user/{username}
          method: get
          cors:
            origin: 'http://localhost:3000'
            headers:
              - Content-Type
              - Authorization
            methods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - .serverless/**
    - .git/**
